require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'wunderBoilerplate' do
  config = use_native_modules!
  use_react_native!( :path => config[:reactNativePath], :hermes_enabled => true )
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end
end